version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - /mnt/storage/jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
    command: bash -c 'echo "jenkins.model.Jenkins.instance.securityRealm.createAccount(\"admin\", \"${JENKINS_ADMIN_PASSWORD}\")" > /usr/share/jenkins/ref/init.groovy.d/initAdmin.groovy && /usr/local/bin/jenkins.sh'
    restart: always


  ssh-agent:
    image: jenkins/ssh-agent
    restart: always
