apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage
    namespace: homepage
    labels:
        app.kubernetes.io/name: homepage
data:
    kubernetes.yaml: |
        mode: cluster
    settings.yaml: |
      title: Welpnetwork Homepage
      favicon: /images/w_logo-tg.png
      background: 
        image: /images/zelda_background.jpeg
      cardBlur: xl
      theme: light
      color: slate
      useEqualHeights: true
      headerStyle: boxed
      layout: 
        tabs : first
        Monitoring:
              tabs: First
              style: row
              columns: 4
              header : false
        Network-Security:
              tabs: Second
              style: row
              columns: 5
              header : false
        Network-Security-Monitored:
              tabs: Third
              style: row
              columns: 4
              header : false
        Application:
              tabs: Fourth
              style: row
              columns: 6
              header : false

    custom.css: ""
    custom.js: ""
    bookmarks.yaml: |
        - Developer:
          - Github Welp99:
              - abbr: GH
                icon: github.svg
                href: https://github.com/welp99

        - DockerHub:
            - DockerHub:
              - abbr: DH
                icon: docker.svg
                href: https://hub.docker.com/u/welp93

        - Entertainment:
            - YouTube:
                - abbr: YT
                  icon: youtube.svg
                  href: https://youtube.com/
    services.yaml: |
        - Monitoring:
            - Proxmox:
                icon: proxmox.svg
                href: https://proxmox.lab.welpnetwork.com:8006
                siteMonitor: https://proxmox.lab.welpnetwork.com:8006
                description: PVE 1
                widget:
                    type: proxmox
                    url: https://proxmox.lab.welpnetwork.com:8006
                    username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
                    password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
                    node: pve
            - Proxmox Backup:
                icon: proxmox.svg
                href: https://pbs.lab.welpnetwork.com:8007
                siteMonitor: https://pbs.lab.welpnetwork.com:8007
                description: Proxmox Backup
                widget:
                    type: proxmoxbackupserver
                    url: https://pbs.lab.welpnetwork.com:8007
                    username: "{{HOMEPAGE_VAR_PROXMOX_BACKUP_USER}}"
                    password: "{{HOMEPAGE_VAR_PROXMOX_BACKUP_API_KEY}}"
                    node: pbs
            - Portainer: 
                icon: portainer.svg
                href: https://portainer-ce.lab.welpnetwork.com
                siteMonitor: https://portainer-ce.lab.welpnetwork.com
                description: Portainer CE
                widget:
                    type: portainer
                    url: https://portainer-ce.lab.welpnetwork.com
                    env: "{{HOMEPAGE_VAR_PORTAINER_ENV}}"
                    key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
            - Uptimekuma:
                icon: https://static-00.iconduck.com/assets.00/uptime-kuma-icon-512x469-ce3ut52z.png
                href: https://uptime-kuma.lab.welpnetwork.com/
                siteMonitor: https://uptime-kuma.lab.welpnetwork.com
                description: Supervision
                widget:
                    type: uptimekuma
                    url: https://uptime-kuma.lab.welpnetwork.com
                    slug: welpnetwork
                    key: "{{ HOMEPAGE_VAR_UPDATEKUMA_API_KEY }}"
        - Network-Security:
            - SophosFW:
                icon: https://cdn.firewall.net.za/wp-content/uploads/2021/01/Sophos.png
                href: https://fw01.welpnetwork.com:4444/
                siteMonitor: https://fw01.welpnetwork.com
                description: Firewall
            - Rancher:
                icon: rancher.svg
                href: https://rancher.lab.welpnetwork.com
                description: K3S Management
            - Elastic: 
                icon: elastic.svg
                href: http://elk.lab.welpnetwork.com
                description: SIEM
            - Passbolt:
                icon: passbolt.svg
                href: https://passbolt.lab.welpnetwork.com
                description: Secret Manager
            - Netbird:
                icon: https://cdn.asp.events/CLIENT_CloserSt_D86EA381_5056_B739_5482D50A1A831DDD/sites/CEEP-2023/media/libraries/exhibitors/156eccdb-6bfb-11ee-bff-06bd0f937899-logo.png/fit-in/500x9999/filters:no_upscale()
                href: https://app.netbird.io/peers
                description: Zerotrust Network
        - Network-Security-Monitored:   
            - Traefik_NESS:
                icon: https://icon.icepanel.io/Technology/svg/Traefik-Proxy.svg
                href: https://traefik-dashboard.lab.welpnetwork.com
                description: Reverse-proxy
                widget:
                    type: traefik
                    url: https://traefik-dashboard.lab.welpnetwork.com
                    username: "{{HOMEPAGE_VAR_TRAEFIK_USERNAME}}"
                    password: "{{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}"
            - Traefik_DMZ:
                icon: https://icon.icepanel.io/Technology/svg/Traefik-Proxy.svg
                href: https://traefik-dashboard3.lab.welpnetwork.com
                description: Reverse-proxy
                widget:
                    type: traefik
                    url: https://traefik-dashboard3.lab.welpnetwork.com
                    username: "{{HOMEPAGE_VAR_TRAEFIK_USERNAME}}"
                    password: "{{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}"
            - Traefik_k3s:
                icon: https://icon.icepanel.io/Technology/svg/Traefik-Proxy.svg
                href: https://traefik.lab.welpnetwork.com
                description: Reverse-proxy
                widget:
                    type: traefik
                    url: https://traefik.lab.welpnetwork.com
                    username: "{{HOMEPAGE_VAR_TRAEFIK_USERNAME}}"
                    password: "{{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}"
            - Authentik: 
                icon: authentik.png
                href: https://auth.lab.welpnetwork.com
                description: Identity Provider
                widget:
                    type: authentik
                    url: https://auth.lab.welpnetwork.com
                    key: "{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}"
            - Pihole:
                icon: https://upload.wikimedia.org/wikipedia/commons/0/00/Pi-hole_Logo.png
                href: https://pihole.lab.welpnetwork.com/
                description: DNS
                widget:
                    type: pihole
                    url: https://pihole.lab.welpnetwork.com
                    key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"
            - Pihole2:
                icon: https://upload.wikimedia.org/wikipedia/commons/0/00/Pi-hole_Logo.png
                href: https://pihole2.lab.welpnetwork.com/admin
                description: DNS
                widget:
                    type: pihole
                    url: https://pihole2.lab.welpnetwork.com
                    key: "{{HOMEPAGE_VAR_PIHOLE_KEY2}}"
            - Grafana: 
                icon: grafana.svg
                href: https://grafana.lab.welpnetwork.com/d/IfgdXjtnk/proxmox-cluster-flux?orgId=1&var-dsProxmox=ddgxl6icufzlse&var-Bucket=proxmox&var-server=All
                description: Monitoring Dashboard
                widget:
                    type: grafana
                    url: https://grafana.lab.welpnetwork.com
                    username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
                    password: "{{HOMEPAGE_VAR_GRAFANA_PASSWD}}"
            - Cloudflare:
                icon: cloudflare.svg
                href: https://one.dash.cloudflare.com/{{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID}}/access/tunnels?search=
                description: Cloudflare Tunnel
                widget:
                    type: cloudflared
                    accountid: "{{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID}}" 
                    tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID}}" 
                    key: "{{HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN}}"
        - Application:
            - Ansible:
                icon: ansible.svg
                href: https://ansible.lab.welpnetwork.com/
                description: Docker Ansible
            - GitLab:
                icon: gitlab.svg
                href: https://gitlab.welpnetwork.com/
                description: Git Homelab
            - Wazuh:
                icon: wazuh.svg
                href: http://wazuh.lab.welpnetwork.com
                description: SOC Homelab
            - Welpnetwork:
                icon: /images/w_logo-tg.png
                href: https://ghost.lab.welpnetwork.com/
                description: Blog
            - Excalidraw:
                icon: excalidraw.svg
                href: https://excalidraw.lab.welpnetwork.com/
                description: Schéma Tool
            - NTFY:
                icon: ntfy.svg
                href: https://ntfy.lab.welpnetwork.com/
                description: Push Notification
            - Plane: 
                icon: jira.svg
                href: https://plane.welpnetwork.com
                description: Project Manager
            - Elastic MSPR:
                icon: elastic.svg
                href: http://elastic-mspr.netbird.cloud
                description: SIEM MSPR
            - Longhorn:
                icon: longhorn.svg
                href: https://rancher.lab.welpnetwork.com/k8s/clusters/local/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/#/dashboard
                description: k3s Storage
            - InfluxDB:
                icon: influxdb.svg
                href: https://influxdb.lab.welpnetwork.com
                description: Metric Database
            - pFsense:
                icon: pfsense.svg
                href: https://192.168.1.46
                description: pfsense MSPR
            - Wazuh:
                icon: wazuh.svg
                href: https://10.10.22.13
                description: SIEM MSPR
        
    widgets.yaml: |
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - resources:
            backend: resources
            expanded: true
            cpu: true
            memory: true
        - search:
            provider: google
            target: _blank
        - datetime:
            text_size: xl
            format:
              timeStyle: short
              hourCycle: h23
    docker.yaml: ""
