---
- name: Deploy vaultwarden with ansible
  hosts: all
  become: yes
  become_user: "{{ lookup('env','USER') }}"
  tasks:
    - name: Pull Docker image
      community.docker.docker_container:
        name: vaultwarden
        image: "docker.io/vaultwarden/server:latest"
      register: image_result
    - name: Stop and remove old Docker container (if applicable)
      docker_container:
        name: vaultwarden
        state: absent
      ignore_errors: yes
    - name: Run Docker container
      docker_container:
        name: vaultwarden
        image: vaultwarden/server:latest
        state: started
        ports:
          - "8130:80"
          - "8543:443"
        volumes:
          - "/mnt/storage/vw-data:/data"
      register: container_result

    - name: Ensure Docker container is running
      debug:
        msg: "Container is running."
      when: container_result.changed