---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: your-domain
  namespace: default
spec:
  secretName: your-domain-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.your-domain.com"
  dnsNames:
  - "your-domain.com"
  - "*.your-domain.com"


