apiVersion: v1
kind: ConfigMap
metadata:
  name: semaphore-config
  namespace: semaphore
data:
  SEMAPHORE_DB_PORT: "3306"
  SEMAPHORE_DB_DIALECT: "mysql"
  SEMAPHORE_DB: "semaphore"
  SEMAPHORE_PLAYBOOK_PATH: "/tmp/semaphore/"
  ANSIBLE_HOST_KEY_CHECKING: "false"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-pvc
  namespace: semaphore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
  namespace: semaphore
spec:
  selector:
    matchLabels:
      app: semaphore
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      containers:
      - name: semaphore
        image: semaphoreui/semaphore:latest
        ports:
        - containerPort: 3000
          name: http
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        readinessProbe:
            httpGet:
              port: 3000
              path: /ping
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 3
        livenessProbe:
          httpGet:
            port: 3000
            path: /
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3
        env:
        - name: SEMAPHORE_DB_USER
          valueFrom:
            secretKeyRef:
              name: semaphore-secret
              key: SEMAPHORE_DB_USER
        - name: SEMAPHORE_DB_PASS
          valueFrom:
            secretKeyRef:
              name: semaphore-secret
              key: SEMAPHORE_DB_PASS
        - name: SEMAPHORE_DB_HOST
          value: mysql
        - name: SEMAPHORE_DB_PORT
          valueFrom:
            secretKeyRef:
              name: semaphore-secret
              key: SEMAPHORE_DB_PORT
        - name: SEMAPHORE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: semaphore-secret
              key: SEMAPHORE_ADMIN_PASSWORD
        - name: SEMAPHORE_ADMIN_NAME
          valueFrom:
            secretKeyRef:
              name: semaphore-secret
              key: SEMAPHORE_ADMIN_EMAIL
        - name: SEMAPHORE_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: semaphore-secret
              key: SEMAPHORE_ADMIN_EMAIL
        - name: SEMAPHORE_ACCESS_KEY_ENCRYPTION
          valueFrom:
            secretKeyRef:
              name: semaphore-secret
              key: SEMAPHORE_ACCESS_KEY_ENCRYPTION
        volumeMounts:
        - name: semaphore-pv
          mountPath: /inventory
        - name: semaphore-pv
          mountPath: /authorized-keys
        - name: semaphore-pv
          mountPath: /etc/semaphore
      volumes:
      - name: semaphore-pv
        persistentVolumeClaim:
          claimName: semaphore-pvc
