version: '3.8'

networks:
  frontend:
    external: true

services:
  webwelp: 
    image: registry.gitlab.com/welpnetwork/webwelp:latest
    container_name: webwelp
    ports:
      - 5000:5000
    restart: always 
    networks:
      - frontend