---
- name: Collect Uptime Information and Append to CSV
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check if Local CSV File Exists
      stat:
        path: /tmp/uptime.csv
      register: csv_file_exists
      delegate_to: localhost

    - name: Delete Local CSV File if Exists
      file:
        path: /tmp/uptime.csv
        state: absent
      when: csv_file_exists.stat.exists

    - name: Get Uptime for All Servers
      command: "uptime -p"
      register: uptime_output

    - name: Append Uptime to CSV
      lineinfile:
        line: "{{ inventory_hostname }},{{ uptime_output.stdout }}"
        path: /tmp/uptime.csv
        create: yes
      delegate_to: localhost

- name: Transfer CSV to Remote Server
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Copy CSV to Remote Server
      copy:
        src: /tmp/uptime.csv
        dest: /path/to/uptime.csv
      delegate_to: <remote_server>

- name: Delete Local CSV File
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Remove Local CSV File
      file:
        path: /tmp/uptime.csv
        state: absent
