---
- name: reboot machine
  hosts: all
  roles: 
      - role: ping
  tasks:
  - name: reboot machine
    reboot:
      reboot_timeout: 3600

  - name: Envoyer une notification
    uri:
      url: https://ntfy.welpnetwork.com/homelab  # Remplacez par l'URL de votre serveur de notification
      method: POST
      body: "Server {{ inventory_hostname }} have been rebooted"  # Décodez le contenu du fichier en base64
      body_format: raw
      headers:
        Content-Type: "text/plain"