version: '3.3'

services:
  uptime-kuma:
      image: louislam/uptime-kuma:latest
      container_name: uptimekuma
      restart: always
      volumes:
      - ./data:/app/data
      ports:
      - '3002:3001'
      env_file: .env
      environment:
        PUID: $PUID
        PGID: $PGID
      networks:
      - frontend

networks:
  frontend:
    external: true