version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    deploy:
      replicas: 1
    volumes:
      - vw-data:/data
    ports:
      - 8130:80
      - 8543:443

volumes:
  vw-data:
